import { EquipmentPosition } from 'src/character/equipment/models/equipment-position.enum';
import { ArmorCategory } from 'src/item/armor/armor-type/models/armor-category.entity';

export const ArmorTypeSeed = [
    {
        name: 'Lion Helmet',
        equipmentPosition: EquipmentPosition.HEAD,
        category: ArmorCategory.HEAVY,
        description: 'The lion king helmet.',
        physicArmor: 50,
        magicArmor: 0,
        minBonusStrength: 0,
        maxBonusStrength: 0,
        minBonusDexterity: 0,
        maxBonusDexterity: 0,
        minBonusIntelligence: 0,
        maxBonusIntelligence: 0,
        minBonusVitality: 100,
        maxBonusVitality: 150,
    },
    {
        name: 'Black Hood',
        equipmentPosition: EquipmentPosition.HEAD,
        category: ArmorCategory.LIGTH,
        description: 'The black hood to be sneaky.',
        physicArmor: 10,
        magicArmor: 0,
        minBonusStrength: 0,
        maxBonusStrength: 0,
        minBonusDexterity: 20,
        maxBonusDexterity: 30,
        minBonusIntelligence: 0,
        maxBonusIntelligence: 0,
        minBonusVitality: 5,
        maxBonusVitality: 10,
    },
    {
        name: 'Iron Armor',
        equipmentPosition: EquipmentPosition.CHEST,
        category: ArmorCategory.HEAVY,
        description: 'A classic iron armor.',
        physicArmor: 40,
        magicArmor: 0,
        minBonusStrength: 5,
        maxBonusStrength: 10,
        minBonusDexterity: 0,
        maxBonusDexterity: 0,
        minBonusIntelligence: 0,
        maxBonusIntelligence: 0,
        minBonusVitality: 20,
        maxBonusVitality: 30,
    },
    {
        name: 'Leather Armor',
        equipmentPosition: EquipmentPosition.CHEST,
        category: ArmorCategory.MEDIUM,
        description: 'A classic leather armor.',
        physicArmor: 30,
        magicArmor: 0,
        minBonusStrength: 2,
        maxBonusStrength: 4,
        minBonusDexterity: 10,
        maxBonusDexterity: 15,
        minBonusIntelligence: 0,
        maxBonusIntelligence: 0,
        minBonusVitality: 1,
        maxBonusVitality: 5,
    },
    {
        name: 'Wizard Dress',
        equipmentPosition: EquipmentPosition.CHEST,
        category: ArmorCategory.LIGTH,
        description: 'A magic wizard dress.',
        physicArmor: 5,
        magicArmor: 25,
        minBonusStrength: 0,
        maxBonusStrength: 0,
        minBonusDexterity: 0,
        maxBonusDexterity: 0,
        minBonusIntelligence: 20,
        maxBonusIntelligence: 25,
        minBonusVitality: 0,
        maxBonusVitality: 5,
    },
    {
        name: 'Jaged Boots',
        equipmentPosition: EquipmentPosition.BOOTS,
        category: ArmorCategory.LIGTH,
        description: 'No one want to walk this that.',
        physicArmor: 0,
        magicArmor: 0,
        minBonusStrength: 0,
        maxBonusStrength: 0,
        minBonusDexterity: 0,
        maxBonusDexterity: 2,
        minBonusIntelligence: 0,
        maxBonusIntelligence: 0,
        minBonusVitality: 0,
        maxBonusVitality: 0,
    },
    {
        name: 'Iron Greaves',
        equipmentPosition: EquipmentPosition.GREAVES,
        category: ArmorCategory.HEAVY,
        description: 'Classic iron greaves.',
        physicArmor: 30,
        magicArmor: 0,
        minBonusStrength: 10,
        maxBonusStrength: 15,
        minBonusDexterity: 0,
        maxBonusDexterity: 0,
        minBonusIntelligence: 0,
        maxBonusIntelligence: 0,
        minBonusVitality: 30,
        maxBonusVitality: 70,
    },
    {
        name: 'Leather Gloves',
        equipmentPosition: EquipmentPosition.GLOVES,
        category: ArmorCategory.MEDIUM,
        description: 'Classic leather gloves.',
        physicArmor: 25,
        magicArmor: 0,
        minBonusStrength: 0,
        maxBonusStrength: 0,
        minBonusDexterity: 2,
        maxBonusDexterity: 10,
        minBonusIntelligence: 0,
        maxBonusIntelligence: 0,
        minBonusVitality: 30,
        maxBonusVitality: 40,
    },
    {
        name: 'Lion Spaulers',
        equipmentPosition: EquipmentPosition.SHOULDERS,
        category: ArmorCategory.HEAVY,
        description: 'The lion king spaulders.',
        physicArmor: 70,
        magicArmor: 0,
        minBonusStrength: 20,
        maxBonusStrength: 30,
        minBonusDexterity: 0,
        maxBonusDexterity: 0,
        minBonusIntelligence: 0,
        maxBonusIntelligence: 0,
        minBonusVitality: 75,
        maxBonusVitality: 150,
    },
    {
        name: 'Cloth Spaulers',
        equipmentPosition: EquipmentPosition.SHOULDERS,
        category: ArmorCategory.LIGTH,
        description: 'Classic cloth spaulders',
        physicArmor: 5,
        magicArmor: 0,
        minBonusStrength: 0,
        maxBonusStrength: 0,
        minBonusDexterity: 0,
        maxBonusDexterity: 0,
        minBonusIntelligence: 10,
        maxBonusIntelligence: 12,
        minBonusVitality: 1,
        maxBonusVitality: 3,
    },
];
