import { EquipmentPosition } from '../character/equipment/models/equipment-position.enum';
import { WeaponCategory } from '../item/weapon/weapon-type/models/weapon-category.enum';
import { WeaponDamageType } from '../item/weapon/weapon-type/models/weapon-damage-type.enum';

export const WeaponTypeSeed = [
    {
        name: 'Great Iron Axe',
        description: 'A big axe for big boys.',
        equipmentPosition: EquipmentPosition.TWO_HANDED,
        category: WeaponCategory.AXE,
        damageType: WeaponDamageType.MELEE_PHYSICAL,
        minimumDamage: 40,
        maximumDamage: 60,
        minBonusStrength: 20,
        maxBonusStrength: 30,
        minBonusDexterity: 0,
        maxBonusDexterity: 0,
        minBonusIntelligence: 0,
        maxBonusIntelligence: 0,
        minBonusVitality: 10,
        maxBonusVitality: 15,
    },
    {
        name: 'Lava Mace',
        description: 'A got mace.',
        equipmentPosition: EquipmentPosition.TWO_HANDED,
        category: WeaponCategory.MACE,
        damageType: WeaponDamageType.MELEE_MAGICAL,
        minimumDamage: 20,
        maximumDamage: 70,
        minBonusStrength: 10,
        maxBonusStrength: 15,
        minBonusDexterity: 0,
        maxBonusDexterity: 0,
        minBonusIntelligence: 12,
        maxBonusIntelligence: 17,
        minBonusVitality: 10,
        maxBonusVitality: 12,
    },
    {
        name: 'Elf Bow',
        description: 'A classic bow.',
        equipmentPosition: EquipmentPosition.TWO_HANDED,
        category: WeaponCategory.BOW,
        damageType: WeaponDamageType.DISTANCE_PHYSICAL,
        minimumDamage: 10,
        maximumDamage: 20,
        minBonusStrength: 0,
        maxBonusStrength: 0,
        minBonusDexterity: 10,
        maxBonusDexterity: 20,
        minBonusIntelligence: 5,
        maxBonusIntelligence: 7,
        minBonusVitality: 0,
        maxBonusVitality: 5,
    },
    {
        name: 'Wand of Poudlard',
        description: 'A wand found in a big wizard school.',
        equipmentPosition: EquipmentPosition.HAND_LEFT,
        category: WeaponCategory.WAND,
        damageType: WeaponDamageType.DISTANCE_MAGICAL,
        minimumDamage: 5,
        maximumDamage: 10,
        minBonusStrength: 0,
        maxBonusStrength: 0,
        minBonusDexterity: 0,
        maxBonusDexterity: 0,
        minBonusIntelligence: 40,
        maxBonusIntelligence: 50,
        minBonusVitality: 20,
        maxBonusVitality: 27,
    },
    {
        name: 'Broken Sword',
        description: 'Only a mad one will use this.',
        equipmentPosition: EquipmentPosition.HAND_RIGHT,
        category: WeaponCategory.SWORD,
        damageType: WeaponDamageType.MELEE_PHYSICAL,
        minimumDamage: 1,
        maximumDamage: 2,
        minBonusStrength: 1,
        maxBonusStrength: 3,
        minBonusDexterity: 0,
        maxBonusDexterity: 0,
        minBonusIntelligence: 0,
        maxBonusIntelligence: 0,
        minBonusVitality: 0,
        maxBonusVitality: 2,
    },
];
